apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        ports:
        - containerPort: {{ .Values.containerPort }}
        name: techtrends
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe }}
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe }}
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
{{ toYaml .Values.resources | indent 10 }}