apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }} 
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: techtrends
    meta.helm.sh/release-namespace: {{ .Values.namespace.name }} 
